# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fasttreeid_identify_bridge <- function(bidirectedSEXP, directedSEXP, seedSEXP, primeSEXP) {
    .Call(`_fasttreeid_fasttreeid_identify_bridge`, bidirectedSEXP, directedSEXP, seedSEXP, primeSEXP)
}

